global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.21.112.1:8080']  # Replace with your actual IP
        labels:
          application: 'banking-service'
    # For Windows, try using the host IP directly
    # Replace 192.168.1.100 with your actual host IP (use ipconfig in cmd to find it)
    # - targets: ['192.168.1.100:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - 'alert.rules'
